// Generated by CodiumAI

describe('fetchDataFromApi', () => {

});

    // Returns expected data format
    it('should return the expected data format when fetchDataFromApi is called', async () => {
      // Mock the axios.get function
      axios.get = jest.fn().mockResolvedValue({ data: { key: 'value' } });

      // Call the fetchDataFromApi function
      const result = await fetchDataFromApi('/api');

      // Assert the result
      expect(result).toEqual({ key: 'value' });

      // Assert that axios.get was called with the correct arguments
      expect(axios.get).toHaveBeenCalledWith(
        process.env.REACT_APP_DEV_URL + '/api',
        params
      );
    });

